import os
import requests
import base64
import time
from message_bus import get_messages, create_message, send_message
from llm import call_llm

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO = os.getenv("REPO_NAME")

HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}


def run_engineer_agent():
    messages = get_messages("engineer")

    spec = None

    for msg in messages:
        if msg["message_type"] == "data":
            spec = msg["payload"]["product_spec"]
            break

    if not spec:
        return

    print("\n👨‍💻 Engineer Agent working...")
    
    # Defaults for failure cases
    issue_url = "N/A"
    pr_url = "N/A"
    
    try:
        # 🔥 1. CLEAN HTML GENERATION
        html = call_llm(f"""
You are a senior frontend developer.

Create a MODERN, CLEAN, PROFESSIONAL landing page.

STRICT REQUIREMENTS:
- Single HTML file only
- Use internal CSS (<style>)
- No external libraries
- Use modern UI design (like startup landing pages)

DESIGN REQUIREMENTS:
- Centered content with max-width layout
- Proper spacing and padding
- Use a clean color palette (dark header + light body)
- Rounded cards for features
- Subtle shadows
- Good typography hierarchy

STRUCTURE:
1. Hero section (headline + subheadline + CTA button)
2. Features section (4 feature cards in grid)
3. Footer

Startup:
{spec}

Return ONLY clean HTML code.
""")

        # 🔥 2. CREATE ISSUE
        if GITHUB_TOKEN and REPO:
            issue_res = requests.post(
                f"https://api.github.com/repos/{REPO}/issues",
                headers=HEADERS,
                json={
                    "title": "Initial landing page",
                    "body": "Generated by Engineer Agent"
                }
            )

            issue_data = issue_res.json()
            print("🔍 Issue Response:", issue_data)
            issue_url = issue_data.get("html_url", "N/A")

            # 🔥 3. GET MAIN BRANCH SHA
            sha_res = requests.get(
                f"https://api.github.com/repos/{REPO}/git/ref/heads/main",
                headers=HEADERS
            )
            sha = sha_res.json()["object"]["sha"]

            # 🔥 4. UNIQUE BRANCH
            branch_name = f"agent-page-{int(time.time())}"

            branch_res = requests.post(
                f"https://api.github.com/repos/{REPO}/git/refs",
                headers=HEADERS,
                json={"ref": f"refs/heads/{branch_name}", "sha": sha}
            )

            if branch_res.status_code != 201:
                print("⚠️ Branch may already exist, continuing...")

            # 🔥 5. COMMIT HTML
            content = base64.b64encode(html.encode()).decode()

            commit_res = requests.put(
                f"https://api.github.com/repos/{REPO}/contents/index.html",
                headers=HEADERS,
                json={
                    "message": "Add landing page",
                    "content": content,
                    "branch": branch_name,
                    "committer": {
                        "name": "EngineerAgent",
                        "email": "agent@launchmind.ai"
                    }
                }
            )

            print("🔍 Commit Response:", commit_res.json())

            # 🔥 6. CREATE PR
            pr_res = requests.post(
                f"https://api.github.com/repos/{REPO}/pulls",
                headers=HEADERS,
                json={
                    "title": "Initial landing page",
                    "body": "Generated by Engineer Agent",
                    "head": branch_name,
                    "base": "main"
                }
            )

            pr_data = pr_res.json()
            print("🔍 PR Response:", pr_data)

            if pr_res.status_code == 201:
                pr_url = pr_data["html_url"]
            elif "A pull request already exists" in pr_data.get("message", ""):
                print("⚠️ PR already exists, fetching existing PR...")
                prs = requests.get(
                    f"https://api.github.com/repos/{REPO}/pulls",
                    headers=HEADERS
                ).json()

                for pr in prs:
                    if pr["head"]["ref"] == branch_name:
                        pr_url = pr["html_url"]
                        break
            else:
                print("❌ PR creation failed")
        else:
            print("⚠️ GitHub credentials not configured")

        print("✅ PR:", pr_url)

    except Exception as e:
        print(f"❌ Engineer Agent Error: {e}")

    # 🔥 7. ALWAYS SEND TO CEO
    send_message(create_message(
        "engineer",
        "ceo",
        "result",
        {
            "issue_url": issue_url,
            "pr_url": pr_url
        }
    ))
